services:
  - type: cron
    name: update-population-data
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python fetch_world_population.py"
    schedule: "0 1 * * *"
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"

  - type: web
    name: population-api
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python api_server.py"
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"

  - type: static
    name: population-chart
    plan: free
    staticPublishPath: public
